spanish-inquisition-4/Battleship_v2

- checkQuality.sh
- src/main/java/com/spanish_inquisition/battleship/Main.java
- src/main/java/com/spanish_inquisition/battleship/client/Client.java
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/common/AppLogger.java
- src/main/java/com/spanish_inquisition/battleship/network/SocketClient.java
- src/main/resources/client/MainMenu.fxml
- src/test/java/com/spanish_inquisition/battleship/MainTest.java
For code reviewers:
We added:
- simple logger for exceptions logging
- simple client GUI with one button
- socket class which will connect to the server
> V2 code review

- README.md
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/main/java/com/spanish_inquisition/battleship/common/Header.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/resources/client/MainMenu.fxml
- src/test/java/com/spanish_inquisition/battleship/client/network/SocketClientTest.java
- src/test/java/com/spanish_inquisition/battleship/common/HeaderTest.java
- src/test/java/com/spanish_inquisition/battleship/server/BattleshipServerTestIT.java
For reviewers:
All the information about current changes is in the commit's messages.
The main concern for this pull request would be corectness of mocking tests
> Client sending name

- .gitignore
- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/main/java/com/spanish_inquisition/battleship/common/AppLogger.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/ClientConnectionHandler.java
- src/test/java/com/spanish_inquisition/battleship/server/BattleshipServerTestIT.java
Do not bother with change to TEST_PORT.
> Handling clients name in server

- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoard.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/main/java/com/spanish_inquisition/battleship/common/AdjacentFieldsCalc.java
- src/main/resources/client/MainMenu.fxml
Most of the classes are just stub classes, with the exception of GameBoardBuilder which has some methods that fill the grid with buttons, so mostly focus on that one.
> Added classes which will operate on the board displayed in the GUI

- RunServerAndTwoClients.sh
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoard.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/main/java/com/spanish_inquisition/battleship/common/AdjacentFieldsCalc.java
- src/main/java/com/spanish_inquisition/battleship/common/Header.java
- src/main/java/com/spanish_inquisition/battleship/common/Styles.java
- src/main/resources/client/MainMenu.fxml
- src/test/java/com/spanish_inquisition/battleship/client/game/GameTest.java
- src/test/java/com/spanish_inquisition/battleship/client/network/SocketClientTest.java
For reviewers: 
In the pull request there are some math methods as well as collecting methods which will need to be checked;
Any suggestions abou the sh file are also very welcome.
> GUI fixes, sh file for run automation

- pom.xml
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
> Dep convergence

- src/main/java/com/spanish_inquisition/battleship/common/Header.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipGame.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/ClientConnectionHandler.java
- src/main/java/com/spanish_inquisition/battleship/server/Message.java
- src/main/java/com/spanish_inquisition/battleship/server/MessageBus.java
- src/main/java/com/spanish_inquisition/battleship/server/ServerMain.java
- src/test/java/com/spanish_inquisition/battleship/server/BattleshipServerTestIT.java
See commit messages for changes in this feuture. Don't mind with changed port in tests. No tests due to code quota exceeded. They will be added later.
> button clicked seen in server code review

- checkQuality.sh
- dev_utils/pre-push
Added two scripts which will prevent the push if any of the command fail.
In order to make the hook work, the dev needs to copy the pre-push file to .git/hooks directory
> Git hooks scripts

- checkQuality.sh
Add opening trello boards during execution of checkQuality script.
> Add opening trello board in checkQuality script

- .gitignore
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/network/ResponsesBus.java
- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/main/java/com/spanish_inquisition/battleship/common/AppLogger.java
- src/main/java/com/spanish_inquisition/battleship/common/NetworkMessage.java
- src/test/java/com/spanish_inquisition/battleship/client/network/ResponsesBusTest.java
- src/test/java/com/spanish_inquisition/battleship/common/ParserTest.java
Client has now a new thread for obtaining server's messages and storing them in the ResponseBus.
The thread is interrupted after a timeout when the closing method is invoked.
Client also has a classes for parsing the server's strings and returning them as a class.
The rest of the commit are simple tests which check if the methods are implemented correctly.
> Response Bus and new Threads

- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/test/java/com/spanish_inquisition/battleship/client/network/SocketClientTest.java
> Added tests for new methods in SocketClient

- src/main/java/com/spanish_inquisition/battleship/server/Players.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/PlacingShipsState.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/GameStateTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/PlayerActionStateTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/ResultStateTest.java
simplified so it has been done.
> Added some tests for code coverage. Method validateFleet() could be

- checkQuality.sh
- src/main/java/com/spanish_inquisition/battleship/client/Client.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoard.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/game/FleetInitializer.java
- src/main/java/com/spanish_inquisition/battleship/common/AdjacentTilesCalc.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipGame.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/EndState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/GameState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/PlacingShipsState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/PlayerActionState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/ShotState.java
- src/test/java/com/spanish_inquisition/battleship/client/board/BoardTileTest.java
- src/test/java/com/spanish_inquisition/battleship/client/board/GameBoardTest.java
- src/test/java/com/spanish_inquisition/battleship/common/TileDirectionTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/PlacingShipsStateTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/ShotStateTest.java
Remove unused imports, bugs found by Intellij and opening trello board in quality script.
> Quality improve

- checkQuality.sh
- src/main/java/com/spanish_inquisition/battleship/client/Client.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoard.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/game/FleetInitializer.java
- src/main/java/com/spanish_inquisition/battleship/common/AdjacentTilesCalc.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipGame.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/EndState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/GameState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/PlayerActionState.java
- src/main/java/com/spanish_inquisition/battleship/server/game_states/ShotState.java
- src/test/java/com/spanish_inquisition/battleship/client/board/BoardTileTest.java
- src/test/java/com/spanish_inquisition/battleship/client/board/GameBoardTest.java
- src/test/java/com/spanish_inquisition/battleship/common/TileDirectionTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/PlacingShipsStateTest.java
- src/test/java/com/spanish_inquisition/battleship/server/game_states/ShotStateTest.java
To eliminate false positive diffs
> Fix diffs between develop and master

- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/main/java/com/spanish_inquisition/battleship/client/network/ResponsesBus.java
- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/main/java/com/spanish_inquisition/battleship/common/Header.java
- src/main/java/com/spanish_inquisition/battleship/common/NetworkMessage.java
- src/test/java/com/spanish_inquisition/battleship/client/MainMenuControllerTest.java
In this pull req there are some tests for fx Controller class and a main game loop.
> Client has a main game loop

- src/main/java/com/spanish_inquisition/battleship/Main.java
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/OpponentBoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/PlayerBoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/game/FleetInitializer.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/main/java/com/spanish_inquisition/battleship/common/AppLogger.java
- src/test/java/com/spanish_inquisition/battleship/client/game/GameTest.java
Opponent's board appears after fleet is sent, started to split opponent and player board conroller into separated classes
Refactor for splitting player and opponent controllers finished
> Opponents board

- checkstyle.xml
- pom.xml
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
Added an xml file with checkstyle config and fixed a bug in Controller
> Checkstyle bugfix

- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/BoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/OpponentBoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/boardcontroller/PlayerBoardController.java
- src/main/java/com/spanish_inquisition/battleship/client/game/FleetInitializer.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/main/java/com/spanish_inquisition/battleship/common/NetworkMessage.java
The game has methods which will send the appropriate message to the
server for a click on the opponent's board;
The game now logs the button's new color;
> The game now reacts to the clicks on the opponent's board

- RunServerAndTwoClientsFromJar.sh
- pom.xml
Change pom to generate jars with server client, add script for running game from jars.
> Generate jars

- src/main/java/com/spanish_inquisition/battleship/client/Client.java
- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/network/ResponsesBus.java
- src/main/java/com/spanish_inquisition/battleship/client/network/SocketClient.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipGame.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/ClientConnectionHandler.java
- src/main/resources/client/MainMenu.fxml
- src/test/java/com/spanish_inquisition/battleship/client/MainMenuControllerTest.java
- src/test/java/com/spanish_inquisition/battleship/client/network/SocketClientTest.java
The client now accepts args as ip address and port number, when absent it gets a default ones which are localhost and port 6666;
> The client now accepts args a a host and port

- src/main/java/com/spanish_inquisition/battleship/client/MainMenuController.java
- src/main/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilder.java
- src/main/java/com/spanish_inquisition/battleship/client/game/Game.java
- src/test/java/com/spanish_inquisition/battleship/client/board/GameBoardBuilderTest.java
Add tests for game board builder. Add method for stopping game loop in class Game.
> Add tests for game board builder; add method for stopping game loop

- src/main/java/com/spanish_inquisition/battleship/client/board/BoardTile.java
- src/main/java/com/spanish_inquisition/battleship/server/BattleshipServer.java
- src/main/java/com/spanish_inquisition/battleship/server/ServerMain.java
- src/test/java/com/spanish_inquisition/battleship/client/board/BoardTileTest.java
- src/test/java/com/spanish_inquisition/battleship/client/board/boardcontroller/BoardControllerTest.java
Added tests for BoardController and BoardTile
> Added tests
